// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using DomainClasses.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // QC_CoileProductivity
    public class CoileProductivity:ISoftDelete
    {
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Wo")]
        public string Wo { get; set; } // WO (length: 20)

        [Required]
        [Display(Name = "Pallet ID")]
        public int PalletId { get; set; } // PalletId

        [Display(Name = "Productivity Source ID")]
        public int ProductivitySourceId { get; set; } // ProductivitySourceId

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Production date")]
        public System.DateTime ProductionDate { get; set; } // ProductionDate

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Creation date")]
        public System.DateTime CreationDate { get; set; } // CreationDate

        [Required]
        [Display(Name = "No of coiles")]
        public int NoOfCoiles { get; set; } // NoOfCoiles

        [Required]
        [Display(Name = "Coile length")]
        public double CoileLength { get; set; } // CoileLength

        [Display(Name = "Total length")]
        public double TotalLength { get; set; } // TotalLength
        [Display(Name = "Non Standard Length")]
        public double NonStdLength { get; set; }

        [Display(Name = "Gross weight")]
        public double? GrossWeight { get; set; } // GrossWeight

        [Display(Name = "Net weight")]
        public double? NetWeight { get; set; } // NetWeight

        [Required(AllowEmptyStrings = true)]
        [MaxLength(24)]
        [StringLength(24)]
        [Display(Name = "Color ID")]
        public string ColorId { get; set; } // ColorId (length: 24)

        [Required]
        [Display(Name = "Has sticker")]
        public bool HasSticker { get; set; } // hasSticker

        [Display(Name = "Notes")]
        public string Notes { get; set; } // Notes

        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Quality status")]
        public string QStatus { get; set; } // QualityStatus (length: 20)

        [DataType(DataType.DateTime)]
        [Display(Name = "QStatus date")]
        public System.DateTime QStatusDate { get; set; } // CreationDate

        [Display(Name = "Member ID")]
        public int? MemberId { get; set; } // MemberId

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Pallet pointed by [QC_CoileProductivity].([PalletId]) (FK_QC_CoileProductivity_QC_Pallet)
        /// </summary>
        public Pallet Pallet { get; set; } // FK_QC_CoileProductivity_QC_Pallet
        public Color Color { get; set; } // FK_QC_CoileProductivity_QC_Pallet
        public ProductivitySource ProductivitySource{ get; set; } // FK_QC_CoileProductivity_QC_Pallet
        public WoHeader WoHeader { get; set; }

        public CoileProductivity()
        {
            IsDeleted = false;
        }
    }

}
// </auto-generated>
