// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using DomainClasses.Entities;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // V_QC_Color
    public class Color
    {
        [Required(AllowEmptyStrings = true)]
        [MaxLength(24)]
        [StringLength(24)]
        [Display(Name = "Id")]
        public string Id { get; set; } // Id (Primary key) (length: 24)

        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Ar name")]
        public string ArName { get; set; } // ArName (length: 255)

        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "En name")]
        public string EnName { get; set; } // EnName (length: 255)

        public ICollection<CoileProductivity> CoileProductivities { get; set; }
        public ICollection<WoHeadersColor> WoHeadersColors { get; set; }
        public ICollection<DrumProductivity> DrumProductivities { get; internal set; }

        public Color()
        {
            CoileProductivities = new List<CoileProductivity>();
            WoHeadersColors = new List<WoHeadersColor>();
            DrumProductivities = new List<DrumProductivity>();
        }
    }

}
// </auto-generated>
