// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using DomainClasses.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // SC_Customer
    public class Customer : ISoftDelete
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; } // ID (Primary key)

        [MaxLength(255)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 50)


        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        public Customer()
        {
            IsDeleted = false;
        }
    }

}
// </auto-generated>

