// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using DomainClasses.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // Ma_Member
    public class Member : ISoftDelete
    {
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 20)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; } // Password (length: 20)

        [MaxLength(50)]
        [StringLength(50)]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; } // Email (length: 50)

        [Required]
        [Display(Name = "Role ID")]
        public int RoleId { get; set; } // RoleID

        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        // Foreign keys

        /// <summary>
        /// Parent Role pointed by [Ma_Member].([RoleId]) (FK_Ma_Member_Ma_Role)
        /// </summary>
        [Required] public Role Role { get; set; } // FK_Ma_Member_Ma_Role

        public Member()
        {
            IsDeleted = false;
        }
    }

}
// </auto-generated>
