// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // QC_Pallets_QualityStatuses
    public class PalletsQualityStatus
    {
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Required]
        [Display(Name = "Pallet ID")]
        public int PalletId { get; set; } // PalletId

        [Required]
        [Display(Name = "Quality status ID")]
        public int QualityStatusId { get; set; } // QualityStatusId

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Quality status date")]
        public System.DateTime QualityStatusDate { get; set; } // QualityStatusDate

        [Display(Name = "Quality status reason")]
        public string QualityStatusReason { get; set; } // QualityStatusReason

        // Foreign keys

        /// <summary>
        /// Parent Pallet pointed by [QC_Pallets_QualityStatuses].([PalletId]) (FK_QC_Pallets_QualityStatuses_QC_Pallet)
        /// </summary>
        public Pallet Pallet { get; set; } // FK_QC_Pallets_QualityStatuses_QC_Pallet

        /// <summary>
        /// Parent QualityStatu pointed by [QC_Pallets_QualityStatuses].([QualityStatusId]) (FK_QC_Pallets_QualityStatuses_QC_QualityStatus)
        /// </summary>
        public QualityStatus QualityStatus { get; set; } // FK_QC_Pallets_QualityStatuses_QC_QualityStatus
    }

}
// </auto-generated>
