// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using DomainClasses.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // QC_Pallet
    public class PalletType : ISoftDelete
    {
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; }

        public int W { get; set; }

        public int L { get; set; }

        public string H { get; set; }


        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        /// <summary>
        /// Child PalletsQualityStatus where [QC_Pallets_QualityStatuses].[PalletId] point to this entity (FK_QC_Pallets_QualityStatuses_QC_Pallet)
        /// </summary>
        public System.Collections.Generic.ICollection<Pallet> Pallets { get; set; } // QC_Pallets

        public PalletType()
        {
            IsDeleted = false;
            Pallets = new System.Collections.Generic.List<Pallet>();
        }
    }

}
// </auto-generated>
