// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using DomainClasses.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // QC_QualityStatus
    public class QualityStatus : ISoftDelete
    {
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "Ar name")]
        public string ArName { get; set; } // ArName (length: 20)

        [MaxLength(20)]
        [StringLength(20)]
        [Display(Name = "En name")]
        public string EnName { get; set; } // EnName (length: 20)

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child PalletsQualityStatus where [QC_Pallets_QualityStatuses].[QualityStatusId] point to this entity (FK_QC_Pallets_QualityStatuses_QC_QualityStatus)
        /// </summary>
        public System.Collections.Generic.ICollection<PalletsQualityStatus> PalletsQualityStatus { get; set; } // QC_Pallets_QualityStatuses.FK_QC_Pallets_QualityStatuses_QC_QualityStatus

        public QualityStatus()
        {
            IsDeleted = false;
            PalletsQualityStatus = new System.Collections.Generic.List<PalletsQualityStatus>();
        }
    }

}
// </auto-generated>
