// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using DomainClasses.Interfaces;
using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // Ma_Role
    public class Role : ISoftDelete
    {
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(25)]
        [StringLength(25)]
        [Display(Name = "En name")]
        public string EnName { get; set; } // EN_Name (length: 25)

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 200)

        [Required]
        [Display(Name = "Is deleted")]
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Functions (Many-to-Many) mapped by table [Ma_Roles_Functions]
        /// </summary>
        public System.Collections.Generic.ICollection<Function> Functions { get; set; } // Many to many mapping
        /// <summary>
        /// Child Members where [Ma_Member].[RoleID] point to this entity (FK_Ma_Member_Ma_Role)
        /// </summary>
        public System.Collections.Generic.ICollection<Member> Members { get; set; } // Ma_Member.FK_Ma_Member_Ma_Role

        public Role()
        {
            IsDeleted = false;
            Members = new System.Collections.Generic.List<Member>();
            Functions = new System.Collections.Generic.List<Function>();
        }
    }

}
// </auto-generated>
