// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace DomainClasses
{

    // V_Ma_WoData
    public class WoData
    {
        [Required]
        [Display(Name = "Id")]
        public int Id { get; set; } // ID (Primary key)
        [MaxLength(120)]
        [StringLength(120)]
        [Display(Name = "Year")]
        public string Year { get; set; } // Year (length: 120)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(120)]
        [StringLength(120)]
        [Display(Name = "Wo")]
        public string Wo { get; set; } // WO (Primary key) (length: 120)

        [MaxLength(240)]
        [StringLength(240)]
        [Display(Name = "Tdsn o")]
        public string TdsNo { get; set; } // TDSNo (length: 240)

        [Required(AllowEmptyStrings = true)]
        [MaxLength(160)]
        [StringLength(160)]
        [Display(Name = "Cable code")]
        public string CableCode { get; set; } // CableCode (Primary key) (length: 160)

        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Customer")]
        public string Customer { get; set; } // Customer (length: 255)

        [MaxLength(510)]
        [StringLength(510)]
        [Display(Name = "Size")]
        public string Size { get; set; } // Size (length: 510)

        [MaxLength(480)]
        [StringLength(480)]
        [Display(Name = "Cable type")]
        public string CableType { get; set; } // CableType (length: 480)

        [MaxLength(160)]
        [StringLength(160)]
        [Display(Name = "Cond type")]
        public string CondType { get; set; } // CondType (length: 160)

        [MaxLength(480)]
        [StringLength(480)]
        [Display(Name = "Standard")]
        public string Standard { get; set; } // Standard (length: 480)

        [MaxLength(240)]
        [StringLength(240)]
        [Display(Name = "Volt")]
        public string Volt { get; set; } // Volt (length: 240)

        [MaxLength(510)]
        [StringLength(510)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 510)

        [Display(Name = "Quantity")]
        public float? Quantity { get; set; } // Quantity

        [MaxLength(96)]
        [StringLength(96)]
        [Display(Name = "Drum")]
        public string Drum { get; set; } // Drum (length: 96)

        [Display(Name = "Stand len")]
        public float? StandLen { get; set; } // StandLen

        [Required]
        [Display(Name = "Out diam")]
        public float OutDiam { get; set; } // OutDiam (Primary key)
    }

}
// </auto-generated>
