// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace DBLayer
{
    using DomainClasses;
    using DomainClasses.Mapping;

    public class ManufacturingContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<ManufacturingContext>
    {
        public ManufacturingContext Create()
        {
            return new ManufacturingContext();
        }
    }
}
// </auto-generated>
