// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace DomainClasses.Mapping
{
    using DomainClasses;

    // QC_CoileProductivity
    public class CoileProductivityConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CoileProductivity>
    {
        public CoileProductivityConfiguration()
            : this("dbo")
        {
        }

        public CoileProductivityConfiguration(string schema)
        {
            ToTable("QC_CoileProductivity", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Wo).HasColumnName(@"WO").HasColumnType("nvarchar").IsRequired().HasMaxLength(20);
            Property(x => x.PalletId).HasColumnName(@"PalletId").HasColumnType("int").IsRequired();
            Property(x => x.ProductionDate).HasColumnName(@"ProductionDate").HasColumnType("datetime").IsRequired();
            Property(x => x.CreationDate).HasColumnName(@"CreationDate").HasColumnType("datetime").IsRequired();
            Property(x => x.NoOfCoiles).HasColumnName(@"NoOfCoiles").HasColumnType("int").IsRequired();
            Property(x => x.CoileLength).HasColumnName(@"CoileLength").HasColumnType("float").IsRequired();
            Property(x => x.TotalLength).HasColumnName(@"TotalLength").HasColumnType("float").IsOptional();
            Property(x => x.NonStdLength).HasColumnName(@"NonStdLength").HasColumnType("float").IsOptional();
            Property(x => x.GrossWeight).HasColumnName(@"GrossWeight").HasColumnType("float").IsOptional();
            Property(x => x.NetWeight).HasColumnName(@"NetWeight").HasColumnType("float").IsOptional();
            Property(x => x.ColorId).HasColumnName(@"ColorId").HasColumnType("nvarchar").IsRequired().HasMaxLength(24);
            Property(x => x.HasSticker).HasColumnName(@"hasSticker").HasColumnType("bit").IsRequired();
            Property(x => x.Notes).HasColumnName(@"Notes").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.QStatus).HasColumnName(@"QStatus").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.QStatusDate).HasColumnName(@"QStatusDate").HasColumnType("datetime").IsOptional();
            Property(x => x.ProductivitySourceId).HasColumnName(@"ProductivitySourceId").HasColumnType("int").IsRequired();
            Property(x => x.MemberId).HasColumnName(@"MemberId").HasColumnType("int").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Pallet).WithMany(b => b.CoileProductivities).HasForeignKey(c => c.PalletId).WillCascadeOnDelete(false); // FK_QC_CoileProductivity_QC_Pallet
            HasRequired(a => a.Color).WithMany(b => b.CoileProductivities).HasForeignKey(c => c.ColorId).WillCascadeOnDelete(false); // FK_QC_CoileProductivity_QC_Pallet
            HasRequired(a => a.ProductivitySource).WithMany(b => b.CoileProductivities).HasForeignKey(c => c.ProductivitySourceId).WillCascadeOnDelete(false); // FK_QC_CoileProductivity_QC_Pallet
            HasRequired(a => a.WoHeader).WithMany(b => b.CoileProductivities).HasForeignKey(c => c.Wo).WillCascadeOnDelete(false); // FK_QC_CoileProductivity_QC_Pallet
        }
    }

}
// </auto-generated>
