// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace DomainClasses.Mapping
{
    using DomainClasses;

    // FinshToStor
    public class DrumProductivityConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DrumProductivity>
    {
        public DrumProductivityConfiguration()
            : this("dbo")
        {
        }

        public DrumProductivityConfiguration(string schema)
        {
            ToTable("FinshToStor", schema);
            HasKey(x => new { x.Wo, x.WoodenNo });

            Property(x => x.Wo).HasColumnName(@"WO").HasColumnType("nvarchar").IsRequired().HasMaxLength(20).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.WoodenNo).HasColumnName(@"DrmNo").HasColumnType("nvarchar").IsRequired().HasMaxLength(20).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SN).HasColumnName(@"WODrm").HasColumnType("int").IsRequired();
            Property(x => x.FcfsId).HasColumnName(@"FCFSId").HasColumnType("int").IsOptional();
            Property(x => x.ProductionDate).HasColumnName(@"cuDat").HasColumnType("datetime").IsRequired();
            Property(x => x.CoilNo).HasColumnName(@"CoilNo").HasColumnType("int").IsOptional();
            Property(x => x.LengthKm).HasColumnName(@"LengthKm").HasColumnType("real").IsRequired();
            Property(x => x.ColorId).HasColumnName(@"ColorID").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.GrossWeight).HasColumnName(@"TotWeight").HasColumnType("real").IsRequired();
            Property(x => x.NetWeight).HasColumnName(@"EmptWeight").HasColumnType("real").IsRequired();
            Property(x => x.Remarks).HasColumnName(@"Remarks").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsOptional();
            Property(x => x.SerCust).HasColumnName(@"SerCust").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.Width).HasColumnName(@"WIDTH").HasColumnType("float").IsOptional();
            Property(x => x.Diameter).HasColumnName(@"DIAMETER").HasColumnType("real").IsOptional();
            Property(x => x.DrumLength).HasColumnName(@"DrumLength").HasColumnType("int").IsOptional();
            Property(x => x.PrintCount).HasColumnName(@"PrintCount").HasColumnType("int").IsRequired();

            HasRequired(a => a.WoHeader).WithMany(b => b.DrumProductivities).HasForeignKey(c => c.Wo).WillCascadeOnDelete(false); // FK_QC_CoileProductivity_QC_Pallet
            HasRequired(a => a.Color).WithMany(b => b.DrumProductivities).HasForeignKey(c => c.ColorId).WillCascadeOnDelete(false); // FK_QC_CoileProductivity_QC_Pallet
        }

    }

}
// </auto-generated>
