// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace DomainClasses.Mapping
{
    using DomainClasses;

    // QC_Pallets_QualityStatuses
    public class PalletsQualityStatusConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PalletsQualityStatus>
    {
        public PalletsQualityStatusConfiguration()
            : this("dbo")
        {
        }

        public PalletsQualityStatusConfiguration(string schema)
        {
            ToTable("QC_Pallets_QualityStatuses", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PalletId).HasColumnName(@"PalletId").HasColumnType("int").IsRequired();
            Property(x => x.QualityStatusId).HasColumnName(@"QualityStatusId").HasColumnType("int").IsRequired();
            Property(x => x.QualityStatusDate).HasColumnName(@"QualityStatusDate").HasColumnType("datetime").IsRequired();
            Property(x => x.QualityStatusReason).HasColumnName(@"QualityStatusReason").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasRequired(a => a.Pallet).WithMany(b => b.PalletsQualityStatus).HasForeignKey(c => c.PalletId).WillCascadeOnDelete(false); // FK_QC_Pallets_QualityStatuses_QC_Pallet
            HasRequired(a => a.QualityStatus).WithMany(b => b.PalletsQualityStatus).HasForeignKey(c => c.QualityStatusId).WillCascadeOnDelete(false); // FK_QC_Pallets_QualityStatuses_QC_QualityStatus
        }
    }

}
// </auto-generated>
