// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace DomainClasses.Mapping
{
    using DomainClasses;

    // QC_QualityStatus
    public class QualityStatusConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<QualityStatus>
    {
        public QualityStatusConfiguration()
            : this("dbo")
        {
        }

        public QualityStatusConfiguration(string schema)
        {
            ToTable("QC_QualityStatus", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ArName).HasColumnName(@"ArName").HasColumnType("nvarchar").IsRequired().HasMaxLength(20);
            Property(x => x.EnName).HasColumnName(@"EnName").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
        }
    }

}
// </auto-generated>
