// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace DomainClasses.Mapping
{
    using DomainClasses;

    // V_Ma_WoData
    public class WoDataConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WoData>
    {
        public WoDataConfiguration()
            : this("dbo")
        {
        }

        public WoDataConfiguration(string schema)
        {
            ToTable("V_Ma_WoData", schema);
            HasKey(x => new { x.Wo, x.CableCode, x.OutDiam });

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Year).HasColumnName(@"Year").HasColumnType("nvarchar").IsOptional().HasMaxLength(120);
            Property(x => x.Wo).HasColumnName(@"WO").HasColumnType("nvarchar").IsRequired().HasMaxLength(120).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TdsNo).HasColumnName(@"TDSNo").HasColumnType("nvarchar").IsOptional().HasMaxLength(240);
            Property(x => x.CableCode).HasColumnName(@"CableCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(160).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Customer).HasColumnName(@"Customer").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Size).HasColumnName(@"Size").HasColumnType("nvarchar").IsOptional().HasMaxLength(510);
            Property(x => x.CableType).HasColumnName(@"CableType").HasColumnType("nvarchar").IsOptional().HasMaxLength(480);
            Property(x => x.CondType).HasColumnName(@"CondType").HasColumnType("nvarchar").IsOptional().HasMaxLength(160);
            Property(x => x.Standard).HasColumnName(@"Standard").HasColumnType("nvarchar").IsOptional().HasMaxLength(480);
            Property(x => x.Volt).HasColumnName(@"Volt").HasColumnType("nvarchar").IsOptional().HasMaxLength(240);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(510);
            Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("real").IsOptional();
            Property(x => x.Drum).HasColumnName(@"Drum").HasColumnType("nvarchar").IsOptional().HasMaxLength(96);
            Property(x => x.StandLen).HasColumnName(@"StandLen").HasColumnType("real").IsOptional();
            Property(x => x.OutDiam).HasColumnName(@"OutDiam").HasColumnType("real").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
        }
    }

}
// </auto-generated>
