// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;

namespace DomainClasses.Mapping
{
    using DomainClasses;

    // V_PL_WOHeader
    public class WoHeaderConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<WoHeader>
    {
        public WoHeaderConfiguration()
            : this("dbo")
        {
        }

        public WoHeaderConfiguration(string schema)
        {
            ToTable("V_PL_WOHeader", schema);
            HasKey(x => x.Wo);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Wo).HasColumnName(@"WO").HasColumnType("nvarchar").IsRequired().HasMaxLength(50).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.OPF).HasColumnName(@"OPF").HasColumnType("nvarchar").IsRequired().HasMaxLength(10).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TdsNo).HasColumnName(@"TDSNo").HasColumnType("nvarchar").IsOptional().HasMaxLength(120);
            Property(x => x.CableCode).HasColumnName(@"CableCode").HasColumnType("nvarchar").IsRequired().HasMaxLength(160).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ConductorType).HasColumnName(@"ConductorType").HasColumnType("nvarchar").IsOptional().HasMaxLength(80);
            Property(x => x.CableType).HasColumnName(@"CableType").HasColumnType("nvarchar").IsOptional().HasMaxLength(240);
            Property(x => x.Standard).HasColumnName(@"Standard").HasColumnType("nvarchar").IsOptional().HasMaxLength(240);
            Property(x => x.Size).HasColumnName(@"Size").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.SizeId).HasColumnName(@"SizeID").HasColumnType("nvarchar").IsOptional().HasMaxLength(10);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Volt).HasColumnName(@"Volt").HasColumnType("nvarchar").IsOptional().HasMaxLength(120);
            Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("real").IsOptional();
            Property(x => x.IsFinished).HasColumnName(@"IsFinished").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DeliveryDate).HasColumnName(@"DeliveryDate").HasColumnType("datetime").IsOptional();
            Property(x => x.Customer).HasColumnName(@"Customer").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.CustomerType).HasColumnName(@"CustomerType").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.StandardLength).HasColumnName(@"StandardLength").HasColumnType("real").IsOptional();

        }
    }

}
// </auto-generated>
